import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dynamic Tic Tac Toe",
  description: "Generated by Tamy",
  icons: {
    icon: "dynamic-tic-tac-toe.svg",
  },
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <link rel="icon" href="dynamic-tic-tac-toe.svg" sizes="any" />
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
